name: Build

on:
  push:
    branches:
      - ci*
    paths-ignore:
      - '.build.yml'
      - '.editorconfig'
      - '.gitignore'
      - LICENSE
      - README.md
  workflow_dispatch:
    inputs:
      c_cpu:
        description: 'Value for gcc -march and -mtune flags.'
        type: choice
        default: znver2
        options:
          - znver2
          - x86-64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Clone repository
      uses: actions/checkout@v5

    - name: Handle inputs
      run: |
        c_cpu=${{ github.event.inputs.c_env_cpu }}
        echo "c_cpu=${c_cpu:-"znver2"}" >> $GITHUB_ENV
    - name: Setup
      uses: ifvlaboratory/.github@main
      with:
        c: true
        c_env_arch: x86
        c_env_cpu: ${{ env.c_cpu }}
        go: true
        pkg_list: 'libsqlite3-0'

    - name: Setup Golang and package cache
      uses: actions/setup-go@v6
      with:
        go-version: 'stable'

    - name: Build
      run: GOFLAGS="$GOFLAGS -tags=libsqlite3" make soju

    - name: Create zstd tar archive
      run: tar cf - soju sojuctl sojudb | zstd -18 -o soju-${{ env.c_cpu }}.tar.zst

    - uses: actions/upload-artifact@v4
      with:
        name: soju-${{ github.sha }}-${{ env.c_cpu }}
        compression-level: 9
        path: |
          soju
          sojuctl
          sojudb

    - uses: softprops/action-gh-release@v2
      with:
        name: 'Nightly build'
        tag_name: 'nightly'
        body: "LOL. try it."
        prerelease: true
        overwrite_files: true
        generate_release_notes: true
        files: soju-${{ env.c_cpu }}.tar.zst
# vim: expandtab
